### ISSUE TITLE
shit werkt niet

### ISSUE THREAD

**Issue by hendiflex** [hendiflex/OssoApp#2]
- clean virtualbox ubuntu 18
- laatste versie node en npm
- project ge git cloned
- npm install
- npm start <- rip

### log
0 info it worked if it ends with ok
1 verbose cli [ '/home/hendi/.nvm/versions/node/v8.11.3/bin/node',
1 verbose cli   '/home/hendi/.nvm/versions/node/v8.11.3/bin/npm',
1 verbose cli   'start' ]
2 info using npm@5.6.0
3 info using node@v8.11.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle OssoApp@0.1.0~prestart: OssoApp@0.1.0
6 info lifecycle OssoApp@0.1.0~start: OssoApp@0.1.0
7 verbose lifecycle OssoApp@0.1.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle OssoApp@0.1.0~start: PATH: /home/hendi/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/hendi/Projects/OssoApp/node_modules/.bin:/home/hendi/.nvm/versions/node/v8.11.3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle OssoApp@0.1.0~start: CWD: /home/hendi/Projects/OssoApp
10 silly lifecycle OssoApp@0.1.0~start: Args: [ '-c', 'react-native-scripts start' ]
11 silly lifecycle OssoApp@0.1.0~start: Returned: code: 1  signal: null
12 info lifecycle OssoApp@0.1.0~start: Failed to exec start script
13 verbose stack Error: OssoApp@0.1.0 start: `react-native-scripts start`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/hendi/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/home/hendi/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid OssoApp@0.1.0
15 verbose cwd /home/hendi/Projects/OssoApp
16 verbose Linux 4.15.0-23-generic
17 verbose argv "/home/hendi/.nvm/versions/node/v8.11.3/bin/node" "/home/hendi/.nvm/versions/node/v8.11.3/bin/npm" "start"
18 verbose node v8.11.3
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error OssoApp@0.1.0 start: `react-native-scripts start`
22 error Exit status 1
23 error Failed at the OssoApp@0.1.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by hendiflex** [comment]
lolnvm
fixed it met: npm start -- --reset-cache
